### ISSUE TITLE
HTTP 400: InvalidTokenFormat (GCM, UCBrowser)

### ISSUE THREAD

**Issue by gbhrdt** [web-push-libs/web-push#318]
```
$ web-push send-notification --endpoint="https://android.googleapis.com/gcm/send/APA91bEYS3yOkXTrcaea1owPL9Y7o5E_Y6YzJF0I_lCSzUk9TUkS-E4lBY9O854en6z5VGTkFZPv_tQRp1UF9q0zd5-jM3SchZsAspKltWkmBMHtBqKwv_zRy6q2RKISuWSiM0nAnUlkobjA9BPw8-hF_OjFsxo74Q" --key="BO8941KKN6yU+3GoVbOX1LftAK9Ax8/s+7QAvALdP5Ab/RMOXw/11NnlQuUCO0KEEJg7xeIA8DzoPcuQZxLH8Lg=" --auth="hs7ccDPZCl8yPG7v+VX0qg==" --payload='{"notification":{"title":"Test","url":"https://google.com"},"channel":{"_id":null},"subscription":{"_id":null}}' --gcm-api-key=<KEY_HERE>
Error sending push message:
{ WebPushError: Received unexpected response code
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/web-push/src/web-push-lib.js:298:20)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  name: 'WebPushError',
  message: 'Received unexpected response code',
  statusCode: 400,
  headers:
   { 'content-type': 'text/html; charset=UTF-8',
     date: 'Thu, 08 Mar 2018 15:55:32 GMT',
     expires: 'Thu, 08 Mar 2018 15:55:32 GMT',
     'cache-control': 'private, max-age=0',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'SAMEORIGIN',
     'x-xss-protection': '1; mode=block',
     server: 'GSE',
     'alt-svc': 'hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="41,39,35"',
     'accept-ranges': 'none',
     vary: 'Accept-Encoding',
     connection: 'close' },
  body: '<HTML>\n<HEAD>\n<TITLE>InvalidTokenFormat</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>InvalidTokenFormat</H1>\n<H2>Error 400</H2>\n</BODY>\n</HTML>\n',
  endpoint: 'https://android.googleapis.com/gcm/send/APA91bEYS3yOkXTrcaea1owPL9Y7o5E_Y6YzJF0I_lCSzUk9TUkS-E4lBY9O854en6z5VGTkFZPv_tQRp1UF9q0zd5-jM3SchZsAspKltWkmBMHtBqKwv_zRy6q2RKISuWSiM0nAnUlkobjA9BPw8-hF_OjFsxo74Q' }
```

I sometimes get an 400 from GCM with 'InvalidTokenFormat' response. We traced the problem down to 'UCBrowser' subscriptions but don't know how to fix it because the endpoints look like a regular GCM endpoint.
Any help is appreciated!

**Comment by marco-c** [comment]
Unfortunately this is definitely not a problem in the library. It could be either a problem in UCBrowser or in GCM (@gauntface any idea?).

**Comment by gbhrdt** [comment]
Thanks for your reply and thanks for closing @marco-c ! I know it's not related to the library but I hope to reach some GCM "experts" or employees here who can help me. Hopefully @gauntface can :-)
