### ISSUE TITLE
Error: read ECONNRESET when use chrome FCM endpoint by Koa

### ISSUE THREAD

**Issue by zoumiaojiang** [web-push-libs/web-push#320]
*Operating System*:  OS X
*Node Version*: 7.10.1 | 8.5.0
*web-push Version*: 3.3.0

- [x] Chrome
- [ ] Firefox
- [ ] Opera for Android
- [ ] Samsung Internet Browser
- [ ] Other

when I use `webpush.sendNotification()` method in my koa server, there is a error when i use chrome (endpoint is FCM) to send a message.

here is the error info:

```
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TLSWrap.onread (net.js:582:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

I check the source code at https://github.com/web-push-libs/web-push/blob/HEAD/src/web-push-lib.js#L289,  I'm not sure if the `https` util have some problem  or  fcm endpoint have some certificate problem? 

by the way, server is localhost and  firefox 59 (autopush) is ok.

show my server code here:

```
const Koa = require('koa');
const app = new Koa();
const cors = require('koa-cors');

const webpush = require('web-push');
app.use(cors());

app.use(async ctx => {
    if (/\/sendproxy\/?$/.test(ctx.path)) {
        let payload = 'some content to push';
        let subscription = {/*...*/};

        webpush.sendNotification(subscription, payload, {
            gcmAPIKey: 'xxxx',
            vapidDetails: {
                subject: 'mailto:xxxx',
                publicKey: 'xxxx',
                privateKey: 'xxxx'
            }
        }).then(res => console.log, err => console.log('----- err: ', err));

        ctx.body = 'send success';
        return;
    }

    ctx.body = '404';
});

app.listen(8081);
```

**Comment by marco-c** [comment]
Are you using a proxy?

**Comment by marco-c** [comment]
Closing for lack of response.

**Comment by Yunnkii** [comment]
我也遇见了相同的错误，使用了 GCM 
```
(node:76181) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:183:27)
(node:76181) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 45)
(node:76181) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:183:27)
(node:76181) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)

```

您的意思是代理有问题，没响应所以出现这种错误？

**Comment by Yunnkii** [comment]
@marco-c

**Comment by Yunnkii** [comment]
@zoumiaojiang 请问您最终是怎么解决的呢，我遇到和您相同的问题

**Comment by thevvh** [comment]
@Yunnkii @zoumiaojiang 请问有解决方案吗？

**Comment by ArikShi96** [comment]
+1. 😞
